[package]
name = "driver"
version.workspace = true
edition.workspace = true
authors.workspace = true
default-run = "driver"

[dependencies]
maschine_library.workspace = true
settings.workspace = true
protocol.workspace = true
arc-swap.workspace = true
hidapi.workspace = true
num.workspace = true
clap.workspace = true
config.workspace = true
serde.workspace = true
toml.workspace = true
libc.workspace = true

midir = { version = "0.11.0", features = ["default"] }


[[bin]]
name = "driver"
path = "src/main.rs"

[[bin]]
name = "gen-default-config"
path = "src/bin/gen_default_config.rs"

[features]
jack = ["midir/jack"]
