[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.5.0"
edition = "2024"
authors = [
    "Juuso Kaitila <Desidiosus@users.noreply.github.com>",
    "Maxime Saddok <saddok.ma@gmail.com>",
    "Viktor Rudnev <me@vrudnev.xyz>",
]

[workspace.dependencies]
maschine_library = { path = "crates/maschine_library" }
settings = { path = "crates/settings" }
protocol = { path = "crates/protocol" }
arc-swap = "1"
ciborium = "0.2"
hidapi = { version = "2.6.5" }
num = { version = "0.4.3" }
num-derive = { version = "0.4.2" }
num-traits = { version = "0.2.19" }
midly = { version = "0.5.3" }
clap = { version = "4.6.1", features = ["derive"] }
config = { version = "0.15.22" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1"
libc = "0.2"
iced = { version = "0.14", features = ["canvas", "image-without-codecs", "svg", "smol"] }
futures = "0.3"
resvg = "0.47"

[workspace.metadata.cargo-shear]
ignored = ["num-traits"]
